name: Deploy to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:
    branches: [main]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      # uses GitHub's checkout action to checkout code from the main branch
      - uses: actions/checkout@v2

      # sets up .NET SDK
      - name: Setup .NET SDK 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "10.0.x"

      # publishes Blazor project to the release folder
      - name: Publish .NET Project
        run: dotnet publish TiC_Online_WASM3/TiC_Online_WASM3.csproj -c Release -o release --nologo

      # copy index.html to 404.html to serve the same file when a file is not found
      - name: copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      # publishes wwwroot directory to GitHub Pages
      - name: Deploy to GitHub Pages (user site)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
          repository-name: thriveinchaosband/thriveinchaosband.github.io
          branch: main
          folder: release/wwwroot
          clean: true
